const CHANNEL1_SWEEP_REGISTER_ADDR = 0xff10;
const CHANNEL1_SOUND_LENGTH_WAVE_PATTERN_DUTY_ADDR = 0xff11;
const CHANNEL1_VOLUME_ENVELOPE_ADDR = 0xff12;
const CHANNEL1_FREQUENCY_LOW_ADDR = 0xff13;
const CHANNEL1_FREQUENCY_HIGHADDR = 0xff14;
const CHANNEL2_SOUND_LENGTH_WAVE_PATTERN_DUTY_ADDR = 0xff16;
const CHANNEL2_VOLUME_ENVELOPE_ADDR = 0xff17;
const CHANNEL2_FREQUENCY_LOW_ADDR = 0xff18;
const CHANNEL2_FREQUENCY_HIGHADDR = 0xff19;
const CHANNEL3_SOUND_ON_OFF__ADDR = 0xff1a;
const CHANNEL3_SOUND_LENGTH_ADDR = 0xff1b;
const CHANNEL3_SELECT_OUTPUT_LEVEL_ADDR = 0xff1c;
const CHANNEL3_FREQUENCY_LOW_ADDR = 0xff1d;
const CHANNEL3_FREQUENCY_HIGHADDR = 0xff1e;
const CHANNEL4_SOUND_LENGTH_ADDR = 0xff20;
const CHANNEL4_VOLUME_ENVELOPE_ADDR = 0xff21;
const CHANNEL4_POLYNOMIAL_COUNTER_ADDR = 0xff22;
const CHANNEL4_COUNTER_CONSECUTIVE_INITIAL_ADDR = 0xff23;
const CHANNEL_CONTROL_ON_OFF_VOLUME = 0xff24;
const SELECT_SOUNT_OUTPUT_TERMINAL = 0xff25;
const SOUND_ON_OFF = 0xff26;

const apu = {};

export default apu;
